# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
#comment for update
include: package:lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.generated.dart"
    - "**/*.gr.dart"
    - "**/*.iconfig.dart"
    - "**/*.p.dart"
    - "**/*.r.dart"
    - "**/*.router.dart"
    - "**/*.template.dart"
    - "**/*.theme.dart"
    - "**/*.w.dart"
    - "**/*.widget.dart"

  errors:
    prefer_const_constructors: warning
    prefer_final_fields: warning

linter:
  rules:
    prefer-single-quotes: false # Optional, based on team preference
    avoid-classes-with-only-static-members: false # Optional, remove if using utility classes

dart_code_metrics:
  metrics:
    number-of-parameters: 4
    maximum-nesting-level: 4
    source-lines-of-code: 100

  rules:
    avoid-unused-parameters
    prefer-const-border-radius
    avoid-global-state
    prefer-extracting-callbacks

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
