services:
  django:
    build: .  # ✅ Forces Docker to build from the local Dockerfile instead of pulling the image
    container_name: backend
    env_file: .env
    volumes:
      - .:/app  # ✅ Mounts local files for live reload
    ports:
      - '8080:8080'
    command:
      [
        'sh',
        '-c',
        'python manage.py migrate --noinput && daphne -b 0.0.0.0 -p 8080 project.asgi:application',
      ]
