services:
  django:
    image: ${DOCKER_HUB_USER:-proppele1}/soen-390-backend:${DOCKER_TAG:-latest} # ✅ Uses branch-based image or defaults to 'latest'
    container_name: backend
    env_file: .env
    volumes:
      - .:/app # ✅ Mounts local files for live reload
    ports:
      - '8080:8080'
    command:
      [
        'sh',
        '-c',
        'python manage.py migrate --noinput && daphne -b 0.0.0.0 -p 8080 project.asgi:application',
      ]
