# Generated by Django 5.1.6 on 2025-02-11 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("location", "0002_initial"),
        ("map", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntranceExit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entrance_exit",
                        to="location.building",
                    ),
                ),
                (
                    "floor_map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entrance_exit",
                        to="map.floormap",
                    ),
                ),
                (
                    "indoor_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_entrance",
                        to="location.indoorpoi",
                    ),
                ),
                (
                    "outdoor_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_exit",
                        to="location.building",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IndoorPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance", models.FloatField()),
                ("estimated_time", models.FloatField()),
                ("is_accessible", models.BooleanField(default=True)),
                (
                    "end",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indoor_end",
                        to="location.indoorlocation",
                    ),
                ),
                (
                    "intermediate",
                    models.ManyToManyField(
                        related_name="indoor_intermediate", to="location.indoorlocation"
                    ),
                ),
                (
                    "start",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indoor_start",
                        to="location.indoorlocation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OutdoorPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance", models.FloatField()),
                ("estimated_time", models.FloatField()),
                (
                    "end",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outdoor_end",
                        to="location.building",
                    ),
                ),
                (
                    "start",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outdoor_start",
                        to="location.building",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_distance", models.FloatField()),
                ("estimated_time", models.FloatField()),
                (
                    "indoor_paths",
                    models.ManyToManyField(
                        related_name="indoor_routes", to="route.indoorpath"
                    ),
                ),
                (
                    "outdoor_paths",
                    models.ManyToManyField(
                        related_name="outdoor_routes", to="route.outdoorpath"
                    ),
                ),
            ],
        ),
    ]
