// Mocks generated by Mockito 5.4.5 from annotations
// in soen_390/test/widgets/screens/place_search_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;

import 'package:geolocator/geolocator.dart' as _i4;
import 'package:latlong2/latlong.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:soen_390/models/outdoor_poi.dart' as _i7;
import 'package:soen_390/models/places.dart' as _i12;
import 'package:soen_390/services/google_maps_api_client.dart' as _i6;
import 'package:soen_390/services/google_poi_service.dart' as _i9;
import 'package:soen_390/services/interfaces/http_client_interface.dart' as _i2;
import 'package:soen_390/services/location_updater.dart' as _i14;
import 'package:soen_390/services/poi_factory.dart' as _i13;
import 'package:soen_390/utils/google_api_helper.dart' as _i3;
import 'package:soen_390/utils/location_service.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIHttpClient_0 extends _i1.SmartFake implements _i2.IHttpClient {
  _FakeIHttpClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoogleApiHelper_1 extends _i1.SmartFake
    implements _i3.GoogleApiHelper {
  _FakeGoogleApiHelper_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGeolocatorPlatform_2 extends _i1.SmartFake
    implements _i4.GeolocatorPlatform {
  _FakeGeolocatorPlatform_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePosition_3 extends _i1.SmartFake implements _i4.Position {
  _FakePosition_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocationSettings_4 extends _i1.SmartFake
    implements _i4.LocationSettings {
  _FakeLocationSettings_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLatLng_5 extends _i1.SmartFake implements _i5.LatLng {
  _FakeLatLng_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoogleMapsApiClient_6 extends _i1.SmartFake
    implements _i6.GoogleMapsApiClient {
  _FakeGoogleMapsApiClient_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePointOfInterest_7 extends _i1.SmartFake
    implements _i7.PointOfInterest {
  _FakePointOfInterest_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocationService_8 extends _i1.SmartFake
    implements _i8.LocationService {
  _FakeLocationService_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GooglePOIService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGooglePOIService extends _i1.Mock implements _i9.GooglePOIService {
  MockGooglePOIService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get apiKey =>
      (super.noSuchMethod(
            Invocation.getter(#apiKey),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#apiKey),
            ),
          )
          as String);

  @override
  _i2.IHttpClient get httpClient =>
      (super.noSuchMethod(
            Invocation.getter(#httpClient),
            returnValue: _FakeIHttpClient_0(
              this,
              Invocation.getter(#httpClient),
            ),
          )
          as _i2.IHttpClient);

  @override
  _i3.GoogleApiHelper get apiHelper =>
      (super.noSuchMethod(
            Invocation.getter(#apiHelper),
            returnValue: _FakeGoogleApiHelper_1(
              this,
              Invocation.getter(#apiHelper),
            ),
          )
          as _i3.GoogleApiHelper);

  @override
  _i11.Future<List<_i12.Place>> getNearbyPlaces({
    required double? latitude,
    required double? longitude,
    required String? type,
    required int? radius,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getNearbyPlaces, [], {
              #latitude: latitude,
              #longitude: longitude,
              #type: type,
              #radius: radius,
            }),
            returnValue: _i11.Future<List<_i12.Place>>.value(<_i12.Place>[]),
          )
          as _i11.Future<List<_i12.Place>>);
}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i8.LocationService {
  MockLocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.GeolocatorPlatform get geolocator =>
      (super.noSuchMethod(
            Invocation.getter(#geolocator),
            returnValue: _FakeGeolocatorPlatform_2(
              this,
              Invocation.getter(#geolocator),
            ),
          )
          as _i4.GeolocatorPlatform);

  @override
  _i4.Position get currentPosition =>
      (super.noSuchMethod(
            Invocation.getter(#currentPosition),
            returnValue: _FakePosition_3(
              this,
              Invocation.getter(#currentPosition),
            ),
          )
          as _i4.Position);

  @override
  set currentPosition(_i4.Position? _currentPosition) => super.noSuchMethod(
    Invocation.setter(#currentPosition, _currentPosition),
    returnValueForMissingStub: null,
  );

  @override
  _i4.LocationSettings get locSetting =>
      (super.noSuchMethod(
            Invocation.getter(#locSetting),
            returnValue: _FakeLocationSettings_4(
              this,
              Invocation.getter(#locSetting),
            ),
          )
          as _i4.LocationSettings);

  @override
  set locSetting(_i4.LocationSettings? _locSetting) => super.noSuchMethod(
    Invocation.setter(#locSetting, _locSetting),
    returnValueForMissingStub: null,
  );

  @override
  bool get serviceEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#serviceEnabled),
            returnValue: false,
          )
          as bool);

  @override
  set serviceEnabled(bool? _serviceEnabled) => super.noSuchMethod(
    Invocation.setter(#serviceEnabled, _serviceEnabled),
    returnValueForMissingStub: null,
  );

  @override
  _i4.LocationPermission get permission =>
      (super.noSuchMethod(
            Invocation.getter(#permission),
            returnValue: _i4.LocationPermission.denied,
          )
          as _i4.LocationPermission);

  @override
  set permission(_i4.LocationPermission? _permission) => super.noSuchMethod(
    Invocation.setter(#permission, _permission),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<bool> isLocationEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isLocationEnabled, []),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> determinePermissions() =>
      (super.noSuchMethod(
            Invocation.method(#determinePermissions, []),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<_i4.Position> getCurrentLocation() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentLocation, []),
            returnValue: _i11.Future<_i4.Position>.value(
              _FakePosition_3(this, Invocation.method(#getCurrentLocation, [])),
            ),
          )
          as _i11.Future<_i4.Position>);

  @override
  _i11.Future<void> updateCurrentLocation() =>
      (super.noSuchMethod(
            Invocation.method(#updateCurrentLocation, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<_i4.Position> getCurrentLocationAccurately() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentLocationAccurately, []),
            returnValue: _i11.Future<_i4.Position>.value(
              _FakePosition_3(
                this,
                Invocation.method(#getCurrentLocationAccurately, []),
              ),
            ),
          )
          as _i11.Future<_i4.Position>);

  @override
  _i11.Future<void> updateCurrentLocationAccurately() =>
      (super.noSuchMethod(
            Invocation.method(#updateCurrentLocationAccurately, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  void takePosition(_i4.Position? p) => super.noSuchMethod(
    Invocation.method(#takePosition, [p]),
    returnValueForMissingStub: null,
  );

  @override
  void setPlatformSpecificLocationSettings() => super.noSuchMethod(
    Invocation.method(#setPlatformSpecificLocationSettings, []),
    returnValueForMissingStub: null,
  );

  @override
  void createLocationStream() => super.noSuchMethod(
    Invocation.method(#createLocationStream, []),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<void> startUp() =>
      (super.noSuchMethod(
            Invocation.method(#startUp, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  void stopListening() => super.noSuchMethod(
    Invocation.method(#stopListening, []),
    returnValueForMissingStub: null,
  );

  @override
  bool checkIfPositionIsAtSGW(_i5.LatLng? coordinates) =>
      (super.noSuchMethod(
            Invocation.method(#checkIfPositionIsAtSGW, [coordinates]),
            returnValue: false,
          )
          as bool);

  @override
  bool checkIfPositionIsAtLOY(_i5.LatLng? coordinates) =>
      (super.noSuchMethod(
            Invocation.method(#checkIfPositionIsAtLOY, [coordinates]),
            returnValue: false,
          )
          as bool);

  @override
  _i11.Stream<_i4.Position> getPositionStream() =>
      (super.noSuchMethod(
            Invocation.method(#getPositionStream, []),
            returnValue: _i11.Stream<_i4.Position>.empty(),
          )
          as _i11.Stream<_i4.Position>);

  @override
  _i5.LatLng convertPositionToLatLng(_i4.Position? p) =>
      (super.noSuchMethod(
            Invocation.method(#convertPositionToLatLng, [p]),
            returnValue: _FakeLatLng_5(
              this,
              Invocation.method(#convertPositionToLatLng, [p]),
            ),
          )
          as _i5.LatLng);

  @override
  _i11.Stream<_i5.LatLng> getLatLngStream() =>
      (super.noSuchMethod(
            Invocation.method(#getLatLngStream, []),
            returnValue: _i11.Stream<_i5.LatLng>.empty(),
          )
          as _i11.Stream<_i5.LatLng>);
}

/// A class which mocks [PointOfInterestFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockPointOfInterestFactory extends _i1.Mock
    implements _i13.PointOfInterestFactory {
  MockPointOfInterestFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.GoogleMapsApiClient get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeGoogleMapsApiClient_6(
              this,
              Invocation.getter(#apiClient),
            ),
          )
          as _i6.GoogleMapsApiClient);

  @override
  _i11.Future<_i7.PointOfInterest> createPointOfInterest({
    required String? placeId,
    required String? imageUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPointOfInterest, [], {
              #placeId: placeId,
              #imageUrl: imageUrl,
            }),
            returnValue: _i11.Future<_i7.PointOfInterest>.value(
              _FakePointOfInterest_7(
                this,
                Invocation.method(#createPointOfInterest, [], {
                  #placeId: placeId,
                  #imageUrl: imageUrl,
                }),
              ),
            ),
          )
          as _i11.Future<_i7.PointOfInterest>);
}

/// A class which mocks [LocationUpdater].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationUpdater extends _i1.Mock implements _i14.LocationUpdater {
  MockLocationUpdater() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.LocationService get service =>
      (super.noSuchMethod(
            Invocation.getter(#service),
            returnValue: _FakeLocationService_8(
              this,
              Invocation.getter(#service),
            ),
          )
          as _i8.LocationService);

  @override
  _i11.Future<_i5.LatLng> getCurrentLatLng() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentLatLng, []),
            returnValue: _i11.Future<_i5.LatLng>.value(
              _FakeLatLng_5(this, Invocation.method(#getCurrentLatLng, [])),
            ),
          )
          as _i11.Future<_i5.LatLng>);
}
