// Mocks generated by Mockito 5.4.5 from annotations
// in soen_390/test/services/campus_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:soen_390/repositories/geojson_repository.dart' as _i3;
import 'package:soen_390/utils/geojson_loader.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGeoJsonLoader_0 extends _i1.SmartFake implements _i2.GeoJsonLoader {
  _FakeGeoJsonLoader_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GeoJsonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeoJsonRepository extends _i1.Mock implements _i3.GeoJsonRepository {
  @override
  _i2.GeoJsonLoader get loader =>
      (super.noSuchMethod(
            Invocation.getter(#loader),
            returnValue: _FakeGeoJsonLoader_0(this, Invocation.getter(#loader)),
            returnValueForMissingStub: _FakeGeoJsonLoader_0(
              this,
              Invocation.getter(#loader),
            ),
          )
          as _i2.GeoJsonLoader);

  @override
  _i4.Future<Map<String, dynamic>> loadBuildingList() =>
      (super.noSuchMethod(
            Invocation.method(#loadBuildingList, []),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> loadBuildingBoundaries() =>
      (super.noSuchMethod(
            Invocation.method(#loadBuildingBoundaries, []),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> loadCampusBoundaries() =>
      (super.noSuchMethod(
            Invocation.method(#loadCampusBoundaries, []),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);
}
