# Generated by Django 5.1.5 on 2025-02-06 02:55

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "location_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="location.location",
                    ),
                ),
                (
                    "boundary",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("num_floors", models.IntegerField(default=1)),
                ("long_name", models.CharField(max_length=255)),
                ("address", models.TextField(default="")),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
            bases=("location.location",),
        ),
        migrations.CreateModel(
            name="IndoorLocation",
            fields=[
                (
                    "location_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="location.location",
                    ),
                ),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
            ],
            bases=("location.location",),
        ),
    ]
