# Generated by Django 5.1.5 on 2025-02-06 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("location", "0001_initial"),
        ("map", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="campus_map",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buildings",
                to="map.campusmap",
            ),
        ),
        migrations.CreateModel(
            name="IndoorPOI",
            fields=[
                (
                    "indoorlocation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="location.indoorlocation",
                    ),
                ),
                ("is_accessible", models.BooleanField(default=True)),
                ("poi_type", models.CharField(max_length=255)),
            ],
            bases=("location.indoorlocation",),
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "indoorlocation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="location.indoorlocation",
                    ),
                ),
                ("room_number", models.CharField(max_length=10)),
                ("room_type", models.CharField(max_length=10)),
            ],
            bases=("location.indoorlocation",),
        ),
        migrations.AddField(
            model_name="indoorlocation",
            name="floor_map",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="indoor_location_set",
                to="map.floormap",
            ),
        ),
    ]
