name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches:
      - main
      - 'feature/**' # ✅ Automatically pushes branch-based images
      - 'hotfix/**'

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-arch builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set DOCKER_TAG
        run: |
            if [[ "${{ github.ref }}" == refs/pull/* ]]; then
              BRANCH_NAME="${{ github.head_ref }}"  # ✅ Use source branch for PRs
            else
              BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's|refs/heads/||')
            fi
            echo "DOCKER_TAG=${BRANCH_NAME}" >> $GITHUB_ENV  # ✅ Set for later steps
        
      - name: Debug Docker Tag
        run: |
            echo "DOCKER_TAG=${DOCKER_TAG}"
        
      - name: Build and Push Docker Image
        run: |
            # Use the developer's Docker Hub username if available, otherwise use default
            DOCKER_HUB_USER=${{ secrets.DOCKER_HUB_USERNAME }}
            IMAGE_TAG="${DOCKER_HUB_USER}/soen-390-backend:${DOCKER_TAG}"
        
            docker buildx build --platform linux/amd64,linux/arm64 \
              -t $IMAGE_TAG --push .
        
