name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches:
      - main
      - 'feature/**' # ✅ Automatically pushes branch-based images
      - 'hotfix/**'

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-arch builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's|refs/heads/||')
          IMAGE_TAG="your-dockerhub-user/soen-390-backend:${BRANCH_NAME}"

          docker buildx build --platform linux/amd64,linux/arm64 \
            -t $IMAGE_TAG --push .
