name: Flutter Testing

on:
  push:
    paths:
      - frontend/**
  pull_request:
    branches:
      - main

jobs:
  testing:
    name: Run Flutter Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          architecture: x64

      - name: Install Flutter dependencies
        working-directory: ./frontend
        run: flutter pub get

      - name: Run Flutter tests with coverage
        working-directory: ./frontend
        run: |
          mkdir -p reports
          flutter test --coverage
          mv coverage/lcov.info reports/lcov.info

      # Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCS_KEY }}

      # Install Google Cloud SDK
      - name: Install Google Cloud SDK
        run: |
          sudo apt-get update && sudo apt-get install -y google-cloud-sdk

      # Upload report to Google Cloud Storage
      - name: Upload report to GCS
        run: |
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///' | tr '/' '_')
          gsutil cp frontend/reports/lcov.info gs://flutter-test-reports/$BRANCH_NAME/lcov.info
