name: Flutter Testing

on:
  push:
    paths:
      - frontend/**
  pull_request:
    branches:
      - main

jobs:
  testing:
    name: Run Flutter Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          architecture: x64

      - name: Install Flutter dependencies
        working-directory: ./frontend
        run: flutter pub get

      - name: Run Flutter tests with coverage
        working-directory: ./frontend
        run: |
          mkdir -p reports
          flutter test --coverage
          mv coverage/lcov.info reports/lcov.info

      # Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCS_KEY }}

      # Install Google Cloud CLI
      - name: Install Google Cloud CLI
        run: |
          sudo apt-get update && sudo apt-get install -y google-cloud-cli

      # Check if the folder exists in GCS before attempting to create it
      - name: Check If Folder Exists in GCS
        run: |
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///' | tr '/' '_')
          
          echo "Checking if folder exists in GCS..."
          if gsutil ls gs://soen_390_reports/$BRANCH_NAME/frontend/ >/dev/null 2>&1; then
            echo "✅ Folder already exists in GCS. Skipping folder creation."
          else
            echo "❌ Folder does not exist. Creating placeholder to maintain structure..."
            echo "Placeholder file" > frontend/reports/.keep
            gsutil -m cp frontend/reports/.keep gs://soen_390_reports/$BRANCH_NAME/frontend/.keep
          fi

      # Upload report to Google Cloud Storage
      - name: Upload Report to GCS
        run: |
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///' | tr '/' '_')
          
          echo "Uploading report to GCS..."
          gsutil -m cp frontend/reports/lcov.info gs://soen_390_reports/$BRANCH_NAME/frontend/lcov.info

          echo "✅ Report successfully uploaded to GCS!"
